# Application configuration for the Auth Service
server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password: sudo0047
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: nzPhnXtBD7CHcNEEKjIrEtN3zRR/6SDafOwgbGAhWhDWIQiopogFfrTt8k9PWBvczlzhoeCOgNajfD8z+fyNYA==
  expiration: 3600

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operations-sorter: alpha
    tags-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
