# Team Service Configuration
server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tinashemutero40@gmail.com
    password: iamtimte.29
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: team-service
  datasource:
    url: jdbc:mysql://localhost:3306/team_db?createDatabaseIfNotExist=true
    username: root
    password: sudo0047
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: nzPhnXtBD7CHcNEEKjIrEtN3zRR/6SDafOwgbGAhWhDWIQiopogFfrTt8k9PWBvczlzhoeCOgNajfD8z+fyNYA==
  expiration: 3600

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operations-sorter: alpha
    tags-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs

USER_SERVICE_URL: http://localhost:8081 
