server:
  port: 8084

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/task_db
    username: root
    password: sudo0047
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
    
